version: '3'

services:
  app:
    image: 'teacherauditing:0.0.1'
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - "9999:9999"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=9999
      - SERVER_ADMIN_BEARER=exodus
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=teacherauditing
      - POSTGRES_USER=teacherauditing
      - POSTGRES_PASSWORD=teacherauditing

  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=teacherauditing
      - POSTGRES_USER=teacherauditing
    ports:
      - "5432:5432"
